language: java
jdk:
  - oraclejdk8
install:
  - mvn clean install
script:
  - mvn test package
  - git config --global user.email "lucky.zhou@xplusz.com"
  - git config --global user.name "LuckyZhou880808"
  - git add target/*
  - git commit -m "build release"
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: "0432de36-a083-4be6-a920-8e8156203411"